pub fn get_weather_art(code: i32) -> Vec<Vec<String>> {
    match code {
        0 => vec![
            vec!["             ".to_string()],
            vec!["    \\   /    ".to_string()],
            vec!["     .-.     ".to_string()],
            vec!["  ― (   ) ―  ".to_string()],
            vec!["     `-’     ".to_string()],
            vec!["    /   \\    ".to_string()],
            vec!["             ".to_string()],
        ],
        1 => vec![
            vec!["             ".to_string()],
            vec!["   \\  /      ".to_string()],
            vec![" _ /\"\".-.    ".to_string()],
            vec!["   \\_(   ).  ".to_string()],
            vec!["   /(___(__) ".to_string()],
            vec!["             ".to_string()],
            vec!["             ".to_string()],
        ],
        2 => vec![
            vec!["             ".to_string()],
            vec!["             ".to_string()],
            vec!["     .--.    ".to_string()],
            vec!["  .-(    ).  ".to_string()],
            vec![" (___.__)__) ".to_string()],
            vec!["             ".to_string()],
            vec!["             ".to_string()],
        ],
        3 => vec![
            vec!["         .-. ".to_string()],
            vec!["        (   )".to_string()],
            vec!["     .--.`-' ".to_string()],
            vec!["  .-(    ).  ".to_string()],
            vec![" (___.__)__) ".to_string()],
            vec!["             ".to_string()],
            vec!["             ".to_string()],
        ],
        45 | 48 => vec![
            vec!["             ".to_string()],
            vec!["             ".to_string()],
            vec![" _ - _ - _ - ".to_string()],
            vec!["  _ - _ - _  ".to_string()],
            vec![" _ - _ - _ - ".to_string()],
            vec!["             ".to_string()],
            vec!["             ".to_string()],
        ],
        51 | 53 | 55 => vec![
            vec!["             ".to_string()],
            vec!["     .--.     ".to_string()],
            vec!["  .-(    ).   ".to_string()],
            vec![" (___.__)__)  ".to_string()],
            vec!["   , '   '    ".to_string()],
            vec!["  ' , '       ".to_string()],
            vec!["             ".to_string()],
        ],
        61 | 63 | 65 => vec![
            vec!["             ".to_string()],
            vec!["     .--.     ".to_string()],
            vec!["  .-(    ).   ".to_string()],
            vec![" (___.__)__)  ".to_string()],
            vec!["   ' ' ' '    ".to_string()],
            vec!["  ' ' ' '     ".to_string()],
            vec!["             ".to_string()],
        ],
        71 | 73 | 75 | 77 => vec![
            vec!["             ".to_string()],
            vec!["     .-.     ".to_string()],
            vec!["    (   ).   ".to_string()],
            vec!["   (___(__)  ".to_string()],
            vec!["    *  *  *  ".to_string()],
            vec!["   *  *  *   ".to_string()],
            vec!["             ".to_string()],
        ],
        80 | 81 | 82 | 85 | 86 => vec![
            vec!["             ".to_string()],
            vec!["     .--.     ".to_string()],
            vec!["  .-(    ).   ".to_string()],
            vec![" (___.__)__)  ".to_string()],
            vec!["  ,',',','    ".to_string()],
            vec![" ,',',','     ".to_string()],
            vec!["             ".to_string()],
        ],
        95 | 96 | 99 => vec![
            vec!["             ".to_string()],
            vec!["     .-.     ".to_string()],
            vec!["    (   ).   ".to_string()],
            vec!["   (___(__)  ".to_string()],
            vec!["    Z\"\"Z \" ".to_string()],
            vec!["  ‚'‚'‚'‚'   ".to_string()],
            vec!["             ".to_string()],
        ],
        _ => vec![
            vec!["             ".to_string()],
            vec!["    .-.      ".to_string()],
            vec!["     __)     ".to_string()],
            vec!["    (        ".to_string()],
            vec!["     `-’     ".to_string()],
            vec!["      •      ".to_string()],
            vec!["             ".to_string()],
        ],
    }
}
